import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />

				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100;0,9..144,200;0,9..144,300;0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;0,9..144,800;0,9..144,900;1,9..144,100;1,9..144,200;1,9..144,300;1,9..144,400;1,9..144,500;1,9..144,600;1,9..144,700;1,9..144,800;1,9..144,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
			</Head>

			<main className="bg-primaryCream">
				<div className="container mx-auto flex flex-row h-[100vh] items-center">
					<div className="flex flex-col md:flex-row mx-auto max-w-[95%] w-[375px] md:w-[620px] relative">
						<div className="w-[100%] md:1/2">
							<img src="/images/image-product-desktop.jpg" className="hidden md:block rounded-tl-xl rounded-bl-xl w-[100%]" />
							<img src="/images/image-product-mobile.jpg" className="md:hidden rounded-t-xl w-[100%]" />
						</div>
						<div className="w-[100%] md:1/2 bg-white p-8 rounded-b-xl md:rounded-tr-xl md:rounded-br-xl flex flex-row items-center">
							<div className="flex flex-col space-y-5">
								<p className="uppercase tracking-[4px] text-[0.825rem] font-montserrat text-darkGrayishBlue">Perfume</p>
								<h1 className="text-[2rem] leading-8 font-fraunces text-veryDarkBlue font-bold">
									Gabrielle Essence Eau De Parfum
								</h1>
								<p className="text-[0.875rem] font-montserrat text-darkGrayishBlue font-medium">
									A floral, solar and voluptuous interpretation composed by Olivier Polge, Perfumer-Creator for the House of CHANEL.
								</p>
								<div className="flex flex-row items-center">
									<p className="text-[2.125rem] text-primaryDarkCyan font-fraunces font-bold pr-7">
										$149.99
									</p>
									<p className="text-[0.8rem] line-through text-darkGrayishBlue font-montserrat text-left font-medium">
										$169.99
									</p>
								</div>
								<button className="bg-primaryDarkCyan rounded-md flex flex-row justify-center items-center pt-[0.8rem] pb-3 transition-all hover:bg-primaryVeryDarkCyan">
									<img src="/images/icon-cart.svg" className="rounded-tl-xl rounded-bl-xl" />
									<p className="font-montserrat text-white pl-2 font-medium text-[0.8rem]">Add to Cart</p>
								</button>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	)
}
